app:
    resource: '@AppBundle/Controller/'
    type: annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        permanent: true
        route: app_battery_log_index
